# Generated by Django 5.0.6 on 2024-05-20 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_bloodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.bloodtype'),
        ),
    ]
