# Generated by Django 5.0.6 on 2024-05-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_user_blood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanDonateTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='can_donate_to', to='blood.bloodtype')),
                ('can_donate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blood.bloodtype')),
            ],
        ),
    ]
