# Generated by Django 5.0.6 on 2024-05-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_candonateto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanReceiveFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='can_receive_from', to='blood.bloodtype')),
                ('can_receive_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.bloodtype')),
            ],
        ),
    ]
