# Generated by Django 5.0.6 on 2024-05-29 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_canreceivefrom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candonateto',
            unique_together={('blood_type', 'can_donate_to')},
        ),
        migrations.AlterUniqueTogether(
            name='canreceivefrom',
            unique_together={('blood_type', 'can_receive_from')},
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_request', models.TextField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('blood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.bloodtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
