# Generated by Django 5.0.6 on 2024-05-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_alter_candonateto_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='address',
            new_name='location',
        ),
    ]
