# Generated by Django 5.0.6 on 2024-08-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_alter_emergency_reason_for_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
