# Generated by Django 5.0.6 on 2024-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_rename_phone_number_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
