# Generated by Django 5.0.6 on 2024-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0014_emergency_latitude_emergency_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
